@startuml 
'!pragma graphviz_dot jdot 
!pragma layout smetana 
entity "Проект" as app_project {
    *"Уникальный код" : "Строка"
---
    "Название" : "Строка"
    "Описание" : "Строка"
    "Статус" : "Строка"
    "Код пользователя" : "Строка"
    "Дата создания" : "Дата/Время"
    "Дата обновления" : "Дата/Время"
}

entity "Задачи" as app_task {
    *"Уникальный код" : "Строка"
---
    "Название" : "Строка"
    "Описание" : "Строка"
    "Статус" : "Строка"
    "Код проекта" : "Строка"
    "Код пользователя" : "Строка"
    "Дата создания" : "Дата/Время"
    "Дата обновления" : "Дата/Время"
}

entity "Пользователь" as app_user {
    *"Уникальный код" : "Строка"
---
    "Имя пользователя" : "Строка"
    "E-mail" : "Строка"
    "Хеш пароля" : "Строка"
    "Имя" : "Строка"
    "Фамилия" : "Строка"
    "Отчество" : "Строка"
    "Дата создания" : "Дата/Время"
    "Дата обновления" : "Дата/Время"
}

entity "Роль" as app_role {
    *"Уникальный код" : "Строка"
---
    "Код пользователя" : "Строка"
    "Тип роли" : "Строка"
    "Дата создания" : "Дата/Время"
    "Дата обновления" : "Дата/Время"
}

"app_project" }--|| "app_user"
"app_task" }--|| "app_project"
"app_task" }--|| "app_user"
"app_role" }--|| "app_user"

@enduml
