@startuml 
'!pragma graphviz_dot jdot
!pragma layout smetana
entity "app_profile" {
    *"id" : "VARCHAR(255)"
---
    "user_id" : "VARCHAR(255)"
    "first_name" : "VARCHAR(255)"
    "last_name" : "VARCHAR(255)"
    "middle_name" : "VARCHAR(255)"
}

entity "app_project" {
    *"id" : "VARCHAR(255)"
---
    "name" : "VARCHAR(255)"
    "description" : "VARCHAR(255)"
    "user_id" : "VARCHAR(255)"
    "status" : "STATUS"
}

entity "app_task" {
    *"id" : "VARCHAR(255)"
---
    "name" : "VARCHAR(255)"
    "description" : "VARCHAR(255)"
    "project_id" : "VARCHAR(255)"
    "user_id" : "VARCHAR(255)"
    "status" : "STATUS"
}

entity "app_user" {
    *"id" : "VARCHAR(255)"
---
    "username" : "VARCHAR(255)"
    "password_hash" : "VARCHAR(255)"
    "email" : "VARCHAR(255)"
}

app_profile ||--|| app_user
app_project }--|| app_user
app_task }--|| app_project
app_task }--|| app_user

@enduml
