@startuml 
'!pragma graphviz_dot jdot 
!pragma layout smetana 
entity "Профиль" as app_profile {
    *"Идентификатор" : "Строка"
---
    "Идентификатор пользователя" : "Строка"
    "Имя" : "Строка"
    "Фамилия" : "Строка"
    "Отчество" : "Строка"
    "Версия" : "Целочисленный"
    "Флаг удаления" : "Логический"
    "Дата создания" : "Дата/Время"
    "Дата обновления" : "Дата/Время"
    "Дата удаления" : "Дата/Время"
    "О себе" : "Строка"
}

entity "Проект" as app_project {
    *"Идентификатор" : "Строка"
---
    "Название" : "Строка"
    "Описание" : "Строка"
    "Идентификатор пользователя" : "Строка"
    "Статус" : "STATUS"
    "Версия" : "Целочисленный"
    "Флаг удаления" : "Логический"
    "Дата создания" : "Дата/Время"
    "Дата обновления" : "Дата/Время"
    "Дата удаления" : "Дата/Время"
}

entity "Задача" as app_task {
    *"Идентификатор" : "Строка"
---
    "Название" : "Строка"
    "Описание" : "Строка"
    "Идентификатор проекта" : "Строка"
    "Идентификатор пользователя" : "Строка"
    "Статус" : "STATUS"
    "Версия" : "Целочисленный"
    "Флаг удаления" : "Логический"
    "Дата создания" : "Дата/Время"
    "Дата обновления" : "Дата/Время"
    "Дата удаления" : "Дата/Время"
}

entity "Пользователь" as app_user {
    *"id" : "Строка"
---
    "Имя пользователя" : "Строка"
    "Хеш пароля" : "Строка"
    "E-mail" : "Строка"
    "Версия" : "Целочисленный"
    "Флаг удаления" : "Логический"
    "Дата создания" : "Дата/Время"
    "Дата обновления" : "Дата/Время"
    "Дата удаления" : "Дата/Время"
}

"app_profile" ||--|| "app_user"
"app_project" }--|| "app_user"
"app_task" }--|| "app_project"
"app_task" }--|| "app_user"

@enduml
