databaseChangeLog:
- changeSet:
    id: 1744123093401-1
    author: volnenko (generated)
    changes:
    - createTable:
        columns:
        - column:
            constraints:
              primaryKey: true
              primaryKeyName: pk_app_profile
            defaultValue: ''
            name: id
            remarks: Идентификатор
            type: VARCHAR(255)
        - column:
            constraints:
              nullable: false
            name: user_id
            remarks: Идентификатор пользователя
            type: VARCHAR(255)
        - column:
            constraints:
              nullable: false
            defaultValue: ''
            name: first_name
            remarks: Имя
            type: VARCHAR(255)
        - column:
            constraints:
              nullable: false
            defaultValue: ''
            name: last_name
            remarks: Фамилия
            type: VARCHAR(255)
        - column:
            constraints:
              nullable: false
            defaultValue: ''
            name: middle_name
            remarks: Отчество
            type: VARCHAR(255)
        remarks: Профиль
        tableName: app_profile
- changeSet:
    id: 1744123093401-2
    author: volnenko (generated)
    changes:
    - createTable:
        columns:
        - column:
            constraints:
              primaryKey: true
              primaryKeyName: pk_app_project
            defaultValue: ''
            name: id
            remarks: Идентификатор
            type: VARCHAR(255)
        - column:
            constraints:
              nullable: false
            defaultValue: ''
            name: name
            remarks: Название
            type: VARCHAR(255)
        - column:
            constraints:
              nullable: false
            defaultValue: ''
            name: description
            remarks: Описание
            type: VARCHAR(255)
        - column:
            name: user_id
            remarks: Идентификатор пользователя
            type: VARCHAR(255)
        - column:
            constraints:
              nullable: false
            defaultValue: NOT_STARTED
            name: status
            remarks: Статус
            type: STATUS
        remarks: Проект
        tableName: app_project
- changeSet:
    id: 1744123093401-3
    author: volnenko (generated)
    changes:
    - createTable:
        columns:
        - column:
            constraints:
              primaryKey: true
              primaryKeyName: pk_app_task
            defaultValue: ''
            name: id
            remarks: Идентификатор
            type: VARCHAR(255)
        - column:
            constraints:
              nullable: false
            defaultValue: ''
            name: name
            remarks: Название
            type: VARCHAR(255)
        - column:
            constraints:
              nullable: false
            defaultValue: ''
            name: description
            remarks: Описание
            type: VARCHAR(255)
        - column:
            name: project_id
            remarks: Идентификатор проекта
            type: VARCHAR(255)
        - column:
            name: user_id
            remarks: Идентификатор пользователя
            type: VARCHAR(255)
        - column:
            constraints:
              nullable: false
            defaultValue: NOT_STARTED
            name: status
            remarks: Статус
            type: STATUS
        remarks: Задача
        tableName: app_task
- changeSet:
    id: 1744123093401-4
    author: volnenko (generated)
    changes:
    - createTable:
        columns:
        - column:
            constraints:
              primaryKey: true
              primaryKeyName: pk_app_user
            defaultValue: ''
            name: id
            type: VARCHAR(255)
        - column:
            constraints:
              nullable: false
            defaultValue: ''
            name: username
            remarks: Имя пользователя
            type: VARCHAR(255)
        - column:
            constraints:
              nullable: false
            defaultValue: ''
            name: password_hash
            remarks: Хеш пароля
            type: VARCHAR(255)
        - column:
            constraints:
              nullable: false
            defaultValue: ''
            name: email
            remarks: E-mail
            type: VARCHAR(255)
        remarks: Пользователь
        tableName: app_user
- changeSet:
    id: 1744123093401-5
    author: volnenko (generated)
    changes:
    - addUniqueConstraint:
        columnNames: user_id
        constraintName: app_profile_user_id_key
        tableName: app_profile
- changeSet:
    id: 1744123093401-6
    author: volnenko (generated)
    changes:
    - addUniqueConstraint:
        columnNames: name, user_id
        constraintName: app_project_name_user_id_key
        tableName: app_project
- changeSet:
    id: 1744123093401-7
    author: volnenko (generated)
    changes:
    - addUniqueConstraint:
        columnNames: email
        constraintName: app_user_email_key
        tableName: app_user
- changeSet:
    id: 1744123093401-8
    author: volnenko (generated)
    changes:
    - addUniqueConstraint:
        columnNames: username
        constraintName: app_user_username_key
        tableName: app_user
- changeSet:
    id: 1744123093401-9
    author: volnenko (generated)
    changes:
    - addForeignKeyConstraint:
        baseColumnNames: user_id
        baseTableName: app_profile
        constraintName: app_profile_user_id_fkey
        deferrable: false
        initiallyDeferred: false
        onDelete: NO ACTION
        onUpdate: NO ACTION
        referencedColumnNames: id
        referencedTableName: app_user
        validate: true
- changeSet:
    id: 1744123093401-10
    author: volnenko (generated)
    changes:
    - addForeignKeyConstraint:
        baseColumnNames: user_id
        baseTableName: app_project
        constraintName: app_project_user_id_fkey
        deferrable: false
        initiallyDeferred: false
        onDelete: NO ACTION
        onUpdate: NO ACTION
        referencedColumnNames: id
        referencedTableName: app_user
        validate: true
- changeSet:
    id: 1744123093401-11
    author: volnenko (generated)
    changes:
    - addForeignKeyConstraint:
        baseColumnNames: project_id
        baseTableName: app_task
        constraintName: app_task_project_id_fkey
        deferrable: false
        initiallyDeferred: false
        onDelete: NO ACTION
        onUpdate: NO ACTION
        referencedColumnNames: id
        referencedTableName: app_project
        validate: true
- changeSet:
    id: 1744123093401-12
    author: volnenko (generated)
    changes:
    - addForeignKeyConstraint:
        baseColumnNames: user_id
        baseTableName: app_task
        constraintName: app_task_user_id_fkey
        deferrable: false
        initiallyDeferred: false
        onDelete: NO ACTION
        onUpdate: NO ACTION
        referencedColumnNames: id
        referencedTableName: app_user
        validate: true
- changeSet:
    id: 1744122711549-14
    author: volnenko (generated)
    changes:
    - addForeignKeyConstraint:
        baseColumnNames: user_id
        baseTableName: app_task
        constraintName: app_task_user_id_fkey
        deferrable: false
        initiallyDeferred: false
        onDelete: NO ACTION
        onUpdate: NO ACTION
        referencedColumnNames: id
        referencedTableName: app_user
        validate: true

