databaseChangeLog:
- changeSet:
    id: 1744104018843-1
    author: volnenko (generated)
    changes:
    - createTable:
        columns:
        - column:
            constraints:
              primaryKey: true
              primaryKeyName: pk_app_project
            defaultValue: ''
            name: id
            remarks: Идентификатор
            type: VARCHAR(255)
        - column:
            constraints:
              nullable: false
            defaultValue: ''
            name: name
            remarks: Название
            type: VARCHAR(255)
        - column:
            constraints:
              nullable: false
            defaultValue: ''
            name: description
            remarks: Описание
            type: VARCHAR(255)
        remarks: Проект
        tableName: app_project
- changeSet:
    id: 1744104018843-2
    author: volnenko (generated)
    changes:
    - createTable:
        columns:
        - column:
            constraints:
              primaryKey: true
              primaryKeyName: pk_app_task
            defaultValue: ''
            name: id
            remarks: Идентификатор
            type: VARCHAR(255)
        - column:
            constraints:
              nullable: false
            defaultValue: ''
            name: name
            remarks: Название
            type: VARCHAR(255)
        - column:
            constraints:
              nullable: false
            defaultValue: ''
            name: description
            remarks: Описание
            type: VARCHAR(255)
        remarks: Задача
        tableName: app_task
- changeSet:
    id: 1744104018843-3
    author: volnenko (generated)
    changes:
    - createTable:
        columns:
        - column:
            constraints:
              primaryKey: true
              primaryKeyName: pk_app_user
            defaultValue: ''
            name: id
            type: VARCHAR(255)
        - column:
            constraints:
              nullable: false
            defaultValue: ''
            name: username
            remarks: Имя пользователя
            type: VARCHAR(255)
        - column:
            constraints:
              nullable: false
            defaultValue: ''
            name: password_hash
            remarks: Хеш пароля
            type: VARCHAR(255)
        - column:
            constraints:
              nullable: false
            defaultValue: ''
            name: email
            remarks: E-mail
            type: VARCHAR(255)
        remarks: Пользователь
        tableName: app_user

